"""Initial migration

Revision ID: 764e9a080d08
Revises: 
Create Date: 2025-04-27 13:00:00.148596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764e9a080d08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('experience', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    # ### end Alembic commands ###
